MARKETING_FILE_PREFIX = "marketing"
USER_FILE_PREFIX = "user"
USER_RECORDS_KEY = "user_records"
AD_RECORDS_KEY = "ad_records"
AD_TABLE_NAME = "ad_events"
USER_TABLE_NAME = "user_events"
EVENTS_TO_TABLE = {
    USER_RECORDS_KEY: USER_TABLE_NAME,
    AD_RECORDS_KEY: AD_TABLE_NAME
}
